---
shell_render_root: "{{ playbook_dir }}/../../.ansible-test-output/shell"
shell_home: "{{ ansible_facts['env']['HOME'] | default(lookup('env', 'HOME')) }}"
shell_dotfiles_root: "{{ playbook_dir }}/../.."
shell_local_dir: "{{ shell_home }}/.local"
shell_opt_dir: "{{ shell_home }}/.local/opt"
shell_macos_homebrew_dir: "/opt/homebrew"
shell_linuxbrew_dir: "/home/linuxbrew/.linuxbrew"
shell_texbin_dir: "/Library/TeX/texbin"
shell_bat_theme: "catppuccin_macchiato"
shell_editor: "nvim"
shell_xdg_config_home: "{{ shell_home }}/.config"
shell_jqp_theme: "catppuccin-macchiato"
shell_oh_my_posh_theme_file: "{{ shell_dotfiles_root }}/oh_my_posh/themes/catppuccin_macchiato.customized.omp.json"
