[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/bash"
args = ["--login"]

[window]
padding.x = 10
padding.y = 10
startup_mode = "Maximized"
decorations = "Buttonless"
opacity = 0.9
blur = true

[scrolling]
history = 100000

[font]
normal.family = "IosevkaTerm Nerd Font"
size = 19
