---
docker_manage: "{{ dotfiles_manage_packages | default(false) }}"
docker_reinstall: false
docker_manage_group_membership: false
docker_user: "{{ ansible_user_id }}"
docker_start_service: "{{ dotfiles_test_environment | default('') != 'docker' }}"
docker_verify_cli: true

docker_apt_keyring_dir: "/etc/apt/keyrings"
docker_apt_keyring_path: "{{ docker_apt_keyring_dir }}/docker.asc"
docker_apt_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_deb_arch_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf
docker_deb_arch: "{{ docker_deb_arch_map.get(ansible_facts['architecture'], ansible_facts['architecture']) }}"
docker_apt_uri: "https://download.docker.com/linux/ubuntu"
docker_apt_suite: "{{ ansible_facts['distribution_release'] }}"
docker_apt_components:
  - stable

docker_prerequisites:
  - ca-certificates
  - curl
  - python3-debian

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_conflicting_packages:
  - docker.io
  - docker-doc
  - docker-compose
  - docker-compose-v2
  - podman-docker
  - containerd
  - runc
