---
#tools_manage_packages: "{{ dotfiles_manage_packages | default(false) }}"

tools_linuxbrew_default_prefix: "/home/linuxbrew/.linuxbrew"
tools_linuxbrew_default_brew: "{{ tools_linuxbrew_default_prefix }}/bin/brew"
tools_brew_bin: ""
tools_manage_ghostty: true

common_tools_formulae:
  - git
  - git-delta
  - diffnav
  - fzf
  - eza
  - bat
  - zoxide
  - oh-my-posh
  - yazi
  - btop
  - glow
  - jqp
  - jq
  - yq
  - xh
  - fd
  - ripgrep

macos_only_tools_formulae:
  - bash
  - bash-completion
  - git-lfs
  - tmux
  - tree

macos_tools_casks:
  - ghostty

ubuntu_apt_packages:
  - bash-completion
  - git-lfs
  - build-essential
  - procps
  - file
  - curl
  - ca-certificates
  - less
  - tmux
  - acpi
  - sysstat
  - lm-sensors
  - tree

ubuntu_only_tools_formulae: []

ubuntu_ghostty_install_method: "ppa"
ubuntu_ghostty_ppa: "ppa:mkasberg/ghostty-ubuntu"

macos_tools_formulae: "{{ common_tools_formulae + macos_only_tools_formulae }}"
ubuntu_tools_formulae: "{{ common_tools_formulae + ubuntu_only_tools_formulae }}"

tools_formula_command_overrides:
  git-delta: delta
  ripgrep: rg
