---
- name: Create shell render directory
  ansible.builtin.file:
    path: "{{ shell_target_root }}"
    state: directory
    mode: "0700"
  when: mode_render | bool

- name: Include macOS login shell tasks
  ansible.builtin.include_tasks: macos.yml
  when:
    - mode_home | bool
    - ansible_facts['system'] == "Darwin"

- name: Render shell files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ shell_target_root }}/{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - src: bashrc.j2
      dest: "{{ shell_bashrc_file }}"
    - src: bash_profile.j2
      dest: "{{ shell_bash_profile_file }}"
    - src: bash_aliases.j2
      dest: "{{ shell_aliases_file }}"
    - src: bash_aliases_local.j2
      dest: "{{ shell_local_aliases_file }}"
      mode: "0600"
    - src: bash_exports.j2
      dest: "{{ shell_exports_file }}"
    - src: functionsrc.j2
      dest: "{{ shell_functions_file }}"
