---
tmux_home: "{{ dot_user_home }}/.tmux"
tmux_target_root: "{{ (dot_render_root ~ '/tmux') if mode_render else dot_user_home }}"

tmux_config_path: "{{ tmux_target_root }}/.tmux.conf"
tmux_plugin_dir: "{{ tmux_home }}/plugins"
tmux_tpm_dir: "{{ tmux_plugin_dir }}/tpm"
tmux_tpm_repo: "https://github.com/tmux-plugins/tpm"
tmux_tpm_version: "master"
tmux_tpm_install_plugins_command: "{{ tmux_tpm_dir }}/bin/install_plugins"
tmux_catppuccin_version: "v2.3.0"
tmux_catppuccin_plugin: "catppuccin/tmux#{{ tmux_catppuccin_version }}"
tmux_catppuccin_flavor: "mocha"
tmux_gpu_plugin: "tmux-revamped/tmux-gpu-revamped"
tmux_gpu_plugin_dir: "{{ tmux_plugin_dir }}/tmux-gpu-revamped"
tmux_gpu_script_path: "{{ tmux_gpu_plugin_dir }}/src/gpu.sh"

tmux_default_terminal: "tmux-256color"
tmux_truecolor_feature: ",*:RGB"
tmux_prefix: "C-a"
tmux_default_shell: "{{ dot_bash_path }}"

tmux_plugins:
  - tmux-plugins/tpm
  - christoomey/vim-tmux-navigator
  - tmux-plugins/tmux-resurrect
  - tmux-plugins/tmux-continuum
  - "{{ tmux_catppuccin_plugin }}"
  - tmux-plugins/tmux-cpu

tmux_extra_plugins: []

tmux_show_cpu: true
tmux_show_ram: true
tmux_show_battery: false
tmux_nvidia_smi_path: "/usr/bin/nvidia-smi"
