---
linuxbrew_default_base: "/home/linuxbrew/.linuxbrew"
linuxbrew_default_bin: "{{ linuxbrew_default_base }}/bin/brew"

ubuntu_apt_packages:
  - bash-completion
  - git-lfs
  - build-essential
  - procps
  - file
  - curl
  - ca-certificates
  - less
  - tmux
  - acpi
  - sysstat
  - lm-sensors
  - tree
  - pciutils
  - wl-clipboard
  - xclip
  - cmake

ubuntu_only_tools_formulae: []

ubuntu_ghostty_install_method: "ppa"
ubuntu_ghostty_apt_keyring_dir: "/etc/apt/keyrings"
ubuntu_ghostty_apt_keyring_path: "{{ ubuntu_ghostty_apt_keyring_dir }}/ghostty.asc"
ubuntu_ghostty_ppa_uri: "https://ppa.launchpadcontent.net/mkasberg/ghostty-ubuntu/ubuntu/"
ubuntu_ghostty_ppa_key_fingerprint: "0721FDF5FECB88DC6920361657C8EF455CEAE491"
ubuntu_ghostty_ppa_key_url: "https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0x{{ ubuntu_ghostty_ppa_key_fingerprint }}"
ubuntu_ghostty_ppa_components:
  - main

ubuntu_tools_formulae: "{{ common_tools_formulae + ubuntu_only_tools_formulae }}"
