---
- name: Dotfiles deployment
  hosts: all
  gather_facts: true

  roles:
    - tools
    - docker
    - gpu
    - shell
    - fonts
    - config
    - terminal
    - git
    - github_ssh
    - tmux
    - neovim
    - document
    - clipboard
