---
neovim_deploy_mode: "test"
neovim_manage_binary: true
neovim_manage_config: true
neovim_manage_plugins: false
neovim_manage_treesitter_parsers: "{{ neovim_deploy_mode == 'home' }}"

neovim_major_minor: "0.12"
neovim_source_config_dir: "{{ role_path }}/files/nvim"

neovim_macos_homebrew_dir: "{{ '/opt/homebrew' if ansible_facts['architecture'] == 'arm64' else '/usr/local' }}"
neovim_linuxbrew_dir: "/home/linuxbrew/.linuxbrew"
neovim_binary_path: "{{ neovim_macos_homebrew_dir ~ '/bin/nvim' if dotfiles_os_family == 'macos' else neovim_linuxbrew_dir ~ '/bin/nvim' if dotfiles_os_family == 'ubuntu' else 'nvim' }}"

neovim_render_root: "{{ playbook_dir }}/../../.ansible-test-output/neovim"
neovim_config_home: "{{ dot_user_home }}/{{ dot_xdg_config_dir | default('.config') }}"
neovim_config_dir: "{{ neovim_config_home }}/nvim"
neovim_config_target_dir: "{{ (neovim_render_root ~ '/config/nvim') if neovim_deploy_mode == 'test' else neovim_config_dir }}"

neovim_headless_xdg_root: "{{ neovim_render_root }}/xdg"
neovim_data_home: "{{ dot_user_home }}/.local/share"
neovim_state_home: "{{ dot_user_home }}/.local/state"
neovim_cache_home: "{{ dot_user_home }}/.cache"
neovim_treesitter_parsers:
  - lua
  - vim
  - javascript
  - html
  - python
  - rust
  - bash
  - csv
  - diff
  - markdown
  - markdown_inline
  - json
  - toml
  - xml
  - yaml
