---
fonts_brew_casks:
  font-anthrosevka-mono: nanxstats/tap/font-anthrosevka-mono
  font-paper-mono-ligaturized: nanxstats/tap/font-paper-mono-ligaturized
  font-iosevka-term-nerd-font: font-iosevka-term-nerd-font
