# Switch the active font by pointing at a profile in ../profiles.
# config-file = ../profiles/font-maple-mono-nf-cn-regular.conf
# config-file = ../profiles/font-iosevka-term.conf
config-file = ../profiles/font-liga-paper-mono.conf
